# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: template
    sensors:
      water_tank_level:
        friendly_name: "Water Tank Level"
        value_template: >
          {% if is_state('binary_sensor.water_tank_d1_mini_water_level_4', 'on') %}
            100
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_3', 'on') %}
            75
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_2', 'on') %}
            50
          {% elif is_state('binary_sensor.water_tank_d1_mini_water_level_1', 'on') %}
            25
          {% else %}
            0
          {% endif %}
        unit_of_measurement: "%"

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  country: IN

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24
  ip_ban_enabled: true
  login_attempts_threshold: 5

# switch:
#   - platform: wake_on_lan
#     name: "Wake Windows Laptop"
#     mac: "A4:B1:C1:A2:56:43"
#     host: "192.168.1.160"
#     turn_off:
#       service: shell_command.sleep_windows_laptop

shell_command:
  git_update: /bin/bash git_update.sh
#   sleep_windows_laptop: 'ssh saksham@192.168.1.160 "RUNDLL32.EXE powrprof.dll,SetSuspendState 0,1,0"'
