# Just need to edit this section now 

substitutions:
  name: outside-32s
  friendly_name: Outside
  key: !secret MCU32S-Outside_key
  ota: !secret MCU32S-Outside_ota
  wifipass: "HAHA2205"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'
  
esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

web_server:

esp32_improv:
  authorizer: none

# Enable Home Assistant API
api:
  encryption:
    key: ${key}

ota:
  - platform: esphome
    password: ${ota}

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: ${wifipass}

captive_portal:
    