# Just need to edit this section now 

substitutions:
  name: bedroom-32s
  friendly_name: Bedroom
  key: !secret MCU32S-Bedroom_key
  ota: !secret MCU32S-Bedroom_ota
  wifipass: "HAHA2205"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: '1.0'

preferences:
  flash_write_interval: 
    minutes: 5

esp32:
  board: nodemcu-32s
  framework:
    type: arduino
    version: recommended

# Enable logging
logger:
  baud_rate: 0

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

web_server:

esp32_improv:
  authorizer: none

# Enable Home Assistant API
api:
  encryption:
    key: ${key}

ota:
  - platform: esphome
    password: ${ota}

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid_1
      password: !secret wifi_password_1
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: ${wifipass}

captive_portal:
    
switch:
  - platform: gpio
    pin: 14                                   
    name: "Fan"                                  
    id: R1
    inverted: yes                          # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF
  
  - platform: gpio
    pin: 27                                   
    name: "LED"                                  
    id: R2
    inverted: yes                           # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: 26                                   
    name: "Tube Light"                                  
    id: R3
    inverted: yes                           # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: 25                                   
    name: "Right Socket"                                  
    id: R4
    inverted: yes                           # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: 33                                   
    name: "Left Socket"                                  
    id: R5
    inverted: yes                           # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: gpio
    pin: 32                                   
    name: "Empty"                                  
    id: R6
    inverted: yes                           # The relay is in active high and needs to be pulled to ground 
    restore_mode: RESTORE_DEFAULT_OFF
  


binary_sensor:

  - platform: gpio
    name: "Right Socket"                                   
    id: S1
    pin:
      number: 19                               
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - delayed_on: 500ms
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: S1
            then:
              - switch.turn_on: R1
            else:
              - switch.turn_off: R1
  
  - platform: gpio
    name: "Left Socket"                                   
    id: S2
    pin:
      number: 18                               
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - delayed_on: 500ms
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: S2
            then:
              - switch.turn_on: R2
            else:
              - switch.turn_off: R2
  
  # - platform: gpio
  #   name: "Fan"                                   
  #   id: S3
  #   pin:
  #     number: 5                               
  #     inverted: True
  #     mode:
  #       input: True
  #       pullup: True
  #   filters:
  #     - delayed_on: 500ms
  #   on_state:
  #     then:
  #       - if:
  #           condition:
  #             - binary_sensor.is_on: S3
  #           then:
  #             - switch.turn_on: R3
  #           else:
  #             - switch.turn_off: R3
  
  - platform: gpio
    name: "Led"                                   
    id: S4
    pin:
      number: 17                               
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - delayed_on: 500ms
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: S4
            then:
              - switch.turn_on: R4
            else:
              - switch.turn_off: R4
  
  - platform: gpio
    name: "Tubelight"                                   
    id: S5
    pin:
      number: 16                               
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - delayed_on: 500ms
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: S5
            then:
              - switch.turn_on: R5
            else:
              - switch.turn_off: R5
  
  - platform: gpio
    name: "Empty"                                   
    id: S6
    pin:
      number: 4                               
      inverted: True
      mode:
        input: True
        pullup: True
    filters:
      - delayed_on: 500ms
    on_state:
      then:
        - if:
            condition:
              - binary_sensor.is_on: S6
            then:
              - switch.turn_on: R6
            else:
              - switch.turn_off: R6
  
  